HYYform/urls.py
from django.contrib import admin
from django.views.generic import TemplateView
from django.urls import path
import xadmin
from category.views import RepairView

urlpatterns = [
    path('xadmin/', xadmin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'),name = 'index'),
    path('demo/',RepairView.as_view(), name='demo')
]

apps/repair/models.py
from datetime import datetime
from django.db import models


from region.models import Region
from category.models import Category
# Create your models here.


class Repair(models.Model):
    SCORE_TYPE = (
        ('1','1'),
        ('2','2'),
        ('3','3'),
        ('4','4'),
        ('5','5')
    )
    name = models.CharField(max_length=100,verbose_name='报修标题')
    username = models.CharField(max_length=15,verbose_name='报修用户')
    userage = models.IntegerField(verbose_name='用户年龄')
    repairregion = models.CharField(max_length=50,verbose_name='报修区域')
    repaircategory = models.CharField(max_length=50,verbose_name='报修分类')
    repairimg = models.ImageField(upload_to="repairimg/",verbose_name='现场图片',null=True,blank=True)
    repaircontent = models.TextField(max_length=500,verbose_name='报修内容')
    worktime = models.IntegerField(verbose_name='处理周期(天)',null=True,blank=True)
    score = models.CharField(choices=SCORE_TYPE,default='5',verbose_name='处理结果评分',max_length=10,null=True,blank=True)
    addtime = models.DateTimeField(default=datetime.now,verbose_name='添加时间')
    status = models.CharField(choices=(('1','处理完成'),('2', '未处理')),default=2, max_length=10,verbose_name='是否完成处理',null=True,blank=True)
    class Meta:
        verbose_name = '报修内容'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

templates/demo.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="initial-scale=1,maximum-scale=1, minimum-scale=1">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="apple-mobile-web-app-capable" content="yes">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
	<title>报修提交</title>
	<style>
		img {
			border: 0;
		}

		body {
			background: #f7f7f7;
			color: #666;
			font: 12px/150% Arial,Verdana, "microsoft yahei";
		}

		html, body, div, dl, dt, dd, ol, ul, li, h1, h2, h3, h4, h5, h6, p, blockquote, pre, button, fieldset, form, input, legend, textarea, th, td {
			margin: 0;
			padding: 0;
		}

		article,aside,details,figcaption,figure,footer,header,main,menu,nav,section,summary {
			display: block;
			margin: 0;
			padding: 0;
		}

		audio,canvas,progress,video {
			display: inline-block;
			vertical-align: baseline;
		}

		a {
			text-decoration: none;
			color: #08acee;
		}

		a:active,a:hover {
			outline: 0;
		}

		button {
			outline: 0;
		}

		mark {
			color: #000;
			background: #ff0;
		}

		small {
			font-size: 80%;
		}

		img {
			border: 0;
		}

		button,input,optgroup,select,textarea {
			margin: 0;
			font: inherit;
			color: inherit;
			outline: none;
		}

		li {
			list-style: none;
		}

		i {
			font-style: normal;
		}

		a {
			color: #666;
		}

		a:hover {
			color: #eee;
		}

		em {
			font-style: normal;
		}

		h2, h3 {
			font-family: "microsoft yahei";
			font-weight: 100;
		}



		/* ------------------- */
		::-moz-placeholder {
			color: #9fa3a7;
		}

		::-webkit-input-placeholder {
			color: #9fa3a7;
		}

		:-ms-input-placeholder {
			color: #9fa3a7;
		}


		.pc-kk-form{
			padding:15px 20px;
		}
		.pc-kk-form-list{
			background:#fff;
			border:1px solid #e5e5e5;
			border-radius:5px;
			height:44px;
			line-height:44px;
			margin-bottom:10px;
		}
		.pc-kk-form-list input{
			width:100%;
			border:none;
			background:none;
			color:#9fa3a7;
			font-size:14px;
			height: 36px;
			padding: 4px 10px;
		}
		.pc-kk-form-list textarea{
			background:none;
			border:none;
			height:60px;
			padding:10px;
			resize:none;
			width:94%;
			line-height:22px;
			color:#9fa3a7;
			font-size:14px;
		}
		.nice-text{
			position: relative;
			background-color:#ffffff;
			width:47%;
			float:left;
			border:1px solid #e5e5e5;
			border-radius:5px;
			height:44px;
			line-height:44px;
		}
		.nice-select{
			position: relative;
			background: #fff url({% static 'images/a2.jpg' %}) no-repeat right center;
			background-size:18px;
			width:47%;
			float:left;
			border:1px solid #e5e5e5;
			border-radius:5px;
			height:44px;
			line-height:44px;
		}

		.nice-select ul{
			width: 100%;
			display: none;
			position: absolute;
			left: -1px;
			top: 44px;
			overflow: hidden;
			background-color: #fff;
			max-height: 150px;
			overflow-y: auto;
			border: 1px solid #b9bcbf;
			z-index: 9999;
			border-radius:5px;

		}
		.nice-select ul li{
			padding-left:10px;
		}
		.nice-select ul li:hover{
			background:#f8f4f4;
		}
		.pc-kk-form-list-clear{
			background:none;
			border:none;
		}
		.pc-kk-form-btn button{
			background:#ec5224;
			color:#fff;
			border:none;
			width:100%;
			height:50px;
			line-height:50px;
			font-size:16px;
			border-radius:50px;
		}
        .errorput{
            border: 1px solid #c40000;
        }
	</style>
</head>
<body>

	<div class="pc-kk-form">
    <div><img src="{% static 'images/1.jpg' %}" style="width:100%;"/></div>
		<form id="email_register_form" method="post" action="{% url 'demo' %}" autocomplete="off" enctype="multipart/form-data">
			<div class="pc-kk-form-list">
				<input type="text" name='name' placeholder="报修标题">
			</div>
			<div class="pc-kk-form-list">
				<input type="text" name='username' placeholder="报修用户">
			</div>
			<div class="pc-kk-form-list pc-kk-form-list-clear">
				<div class="nice-text" name="nice-select">
					<input type="text" name="userage" placeholder="年龄" >

				</div>
				<div class="nice-select" name="nice-select" style="float:right">
					<input type="text" name="repairregion" placeholder="报修区域" readonly>
					<ul>
                        {% for names in region_name %}
						<li data-value="male">{{ names.name }}</li>
                        {% endfor %}
					</ul>

				</div>
			</div>

			<div class="pc-kk-form-list pc-kk-form-list-clear">
				<div class="nice-select" name="nice-select" style="width:100%">
					<input type="text" name='repaircategory' placeholder="报修类型" readonly>
					<ul>
                        {% for categorya in category_names %}
						<li data-value="Level1">{{ categorya.name }}</li>
                        {% endfor %}
					</ul>
				</div>
			</div>

            <div class="pc-kk-form-list" style="height:auto">
				<input type="text" name='repaircontent' placeholder="报修内容" >
			</div>
			<div class="pc-kk-form-list">
				<input type="tel" placeholder="处理周期">
			</div>
			<div class="pc-kk-form-list pc-kk-form-list-clear">
				<div class="nice-select" name="nice-select">
					<input type="text" placeholder="是否处理完成" readonly>
					<ul>
                        {% for repair_status in repair_names %}
						<li data-value="time1">{{ repair_status.get_status_display}} </li>
						{% endfor %}
					</ul>
				</div>
				<div class="nice-select" name="nice-select" style="float:right">
					<input type="text" value="结果反馈评分" readonly>
					<ul>
						{% for repair_status in repair_names %}
						<li data-value="time1">{{ repair_status.get_score_display}} </li>
						{% endfor %}
					</ul>

				</div>
			</div>

			<div class="pc-kk-form-btn">
				<button><input class="btn btn-green"  type="submit" value="提交" /></button>
			</div>
        {% csrf_token %}
		</form>


	</div>


	<script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>

	<script>





        $('[name="nice-select"]').click(function(e){

            $('[name="nice-select"]').find('ul').hide();

            $(this).find('ul').show();

            e.stopPropagation();

        });

        $('[name="nice-select"] li').hover(function(e){

            $(this).toggleClass('on');

            e.stopPropagation();

        });

        $('[name="nice-select"] li').click(function(e){

            var val = $(this).text();

            $(this).parents('[name="nice-select"]').find('input').val(val);

            $('[name="nice-select"] ul').hide();

            e.stopPropagation();

        });

        $(document).click(function(){

            $('[name="nice-select"] ul').hide();

        });

	</script>

</body>
</html>

templates/index.html
<!doctype html>
<html>
{% load staticfiles %}
<head>
    <meta charset="utf-8">
    <title>报修数据概览</title>
    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/comon0.css' %}">
</head>
<script>
    $(window).load(function () {
        $(".loading").fadeOut()
    })


    $(document).ready(function () {
        var whei = $(window).width()
        $("html").css({fontSize: whei / 20})
        $(window).resize(function () {
            var whei = $(window).width()
            $("html").css({fontSize: whei / 20})
        });
    });
</script>
<script type="text/javascript" src="{% static 'js/echarts.min.js' %}"></script>
<script language="JavaScript" src="{% static 'js/js.js' %}"></script>
<body>
<div class="canvas" style="opacity: .2">
    <iframe frameborder="0" src="{% static 'js/index.html' %}" style="width: 100%; height: 100%"></iframe>
</div>
<div class="loading">
    <div class="loadbox"><img src="{% static 'images/loading.gif' %}"> 页面加载中...</div>
</div>
<div class="head">
    <h1>鸿运苑二社区一体化管理情况数据统计</h1>
    <div class="weather"><!--<img src="images/weather.png"><span>多云转小雨</span>--><span id="showTime"></span></div>

    <script>
        var t = null;
        t = setTimeout(time, 1000);

        function time() {
            clearTimeout(t);
            dt = new Date();
            var y = dt.getFullYear();
            var mt = dt.getMonth() + 1;
            var day = dt.getDate();
            var h = dt.getHours();
            var m = dt.getMinutes();
            var s = dt.getSeconds();
            document.getElementById("showTime").innerHTML = y + "年" + mt + "月" + day + "日  " + h + "：" + m + "：" + s ;
            t = setTimeout(time, 1000);
        }

    </script>


</div>
<div class="mainbox">
    <ul class="clearfix">
        <li>
            <div class="boxall" style="height: 3.2rem">
                <div class="alltitle">报修重复率<span>（次/月）</span></div>
                <div class="allnav" id="echart1"></div>
                <div class="boxfoot"></div>
            </div>
            <div class="boxall" style="height: 3.2rem">
                <div class="alltitle">当周报修频率</div>
                <div class="allnav" id="echart2"></div>
                <div class="boxfoot"></div>
            </div>
            <div class="boxall" style="height: 3.2rem">
                <div style="height:100%; width: 100%;">
                    <div class="sy" id="fb1"></div>
                    <div class="sy" id="fb2"></div>
                    <div class="sy" id="fb3"></div>
                </div>
                <div class="boxfoot">

                </div>
            </div>
        </li>
        <li>
            <div class="bar">
                <div class="barbox">
                    <ul class="clearfix">
                        <li class="pulll_left counter">1281189</li>
                        <li class="pulll_left counter">912410</li>
                    </ul>
                </div>
                <div class="barbox2">
                    <ul class="clearfix">
                        <li class="pulll_left">2018年总上报问题数量</li>
                        <li class="pulll_left">2018年总处理解决问题数量</li>
                    </ul>
                </div>
            </div>
            <div class="map">
                <div class="map1"><img src="{% static 'images/lbx.png' %}"></div>
                <div class="map2"><img src="{% static 'images/jt.png' %}"></div>
                <div class="map3"><img src="{% static 'images/map.png' %}"></div>
                <div class="map4" id="map_1"></div>
            </div>
        </li>
        <li>
            <div class="boxall" style="height:3.4rem">
                <div class="alltitle">报修满意度</div>
                <div class="allnav" id="echart4"></div>
                <div class="boxfoot"></div>
            </div>
            <div class="boxall" style="height: 3.2rem">
                <div class="alltitle">报修处理周期<span >（天）</span></div>
                <div class="allnav" id="echart5"></div>
                <div class="boxfoot"></div>
            </div>
            <div class="boxall" style="height: 3rem">
                <div class="alltitle">管辖区域问题上报数</div>
                <div class="allnav" id="echart6"></div>
                <div class="boxfoot"></div>
            </div>
        </li>
    </ul>
</div>
{% for names in names %}
{{ names.name }}
{% endfor %}
{% for region in regionname %}
{{ region.name }}
{% endfor %}
<div class="back">{{ msg }}</div>


<script type="text/javascript" src="{% static 'js/china.js' %}"></script>
<script type="text/javascript" src="{% static 'js/area_echarts.js' %}"></script>


</body>
</html>